### ISSUE TITLE
Enhancement: Option to add/remove all modules to/from a recipe

### ISSUE THREAD

**Issue by randomflyingtaco** [LovelySanta/FactorioModLib#4]
https://github.com/LovelySanta/FactorioModLib/blob/master/LSlib/prototyping/recipe/recipe-module.lua
canUseModuleEffect and removeModuleEffect only work if you give them a list of modules, but it would be nice to have an add/remove all option, either as what happens when you have nil as the first parameter or as separate functions.

**Comment by LovelySanta** [comment]
> canUseModuleEffect and removeModuleEffect only work if you give them a list of modules

Let's start with `LSlib.recipe.canUseModuleEffect(...)`. As you see in the code below, in case you pass in a table of modules, it will iterate over each module seperate (line 41). This does mean that it does work for sure for a single module as well. It would be weird to pass in nil as first parameter since you want to change something on a recipe, but you're not sure what recipe you want to change? Sounds like a bit counter intuitive... In that case you can easily enclose the function call with an if statement to check if it's not nil. I could however return `nil`, so I might add that.

https://github.com/LovelySanta/FactorioModLib/blob/9e3dbea11272404a2f786387a944b5e99e01934a/LSlib/prototyping/recipe/recipe-module.lua#L36-L54

Next is the `LSlib.recipe.removeModuleEffect(...)`. Again, as you can see on line 73, it will iterate through each module if you pass in a table, similarly to the previous fuction, where I explained it in a bit more detail. So here I could as well add an early return in case you pass `nil` as recipeName.

https://github.com/LovelySanta/FactorioModLib/blob/9e3dbea11272404a2f786387a944b5e99e01934a/LSlib/prototyping/recipe/recipe-module.lua#L69-L85

> it would be nice to have an add/remove all option

I do not want to add in extra overhead for when you pass in no modules at all... In that case, I might add a function `LSlib.item.getModuleNames(...)` that extracts a table with all moduleNames from `data.raw["module"]`. This way you can pass in this table to the functions in order to do it for all modules.

How does that sounds to you?

**Comment by randomflyingtaco** [comment]
My bad, in the original post I meant allowModuleEffect and removeModuleEffect.  So that you could call the new functions to allow all modules (modules that have limitations, of course) or disallow all modules (that have limitations).
I seems like it would be nicer to be able to call a library function instead each mod setting up their own separate loops to look through all modules with limitations.

**Comment by LovelySanta** [comment]
Ah I see, so what about the function `LSlib.item.getAllModuleNames(limitationOnly)` such that it would be able to give you a full list or a list with all modules with limitations?

Then I could also make a default for the functions `allowModuleEffect(...)`, `canUseModuleEffect(...)` and `removeModuleEffect(...)` to use a defult value of a list with modules when you pass moduleNames as a nil value.

Of course, `canUseModuleEffect(...)` would have a default of all modules, while the other two would only have a default list of modules with limitations.

**Comment by randomflyingtaco** [comment]
Makes sense to me.  So far, I only intend to use allowModuleEffect and removeModuleEffect, and having an option to default them to all modules would save some for loops and make things more readable.

**Comment by LovelySanta** [comment]
I'll work on this when updating some other mods. Focussing on an exam for university first.

**Comment by LovelySanta** [comment]
Implemented in https://github.com/LovelySanta/FactorioModLib/commit/ab40a1582bc360123b8f07f8a59eb710abee0c34.
